### ISSUE TITLE
Change Class Components to Functional Components

### ISSUE THREAD

**Issue by ibrahimrehman1** [ibrahimrehman1/React-Calculator-App#1]
I am currently using **Class Components** in this React Application. Change the Class Components to **Functional Components**

**Comment by theprogrammerinyou** [comment]
Can I work on this?

**Comment by theprogrammerinyou** [comment]
Please assign it to me

**Comment by ibrahimrehman1** [comment]
Yeah Sure!

**Comment by theprogrammerinyou** [comment]
Can you add hacktoberfest as label to the repository?

**Comment by ibrahimrehman1** [comment]
> Can you add hacktoberfest as label to the repository?

Sure

**Comment by theprogrammerinyou** [comment]
In the class components earlier you wrote bind functions for state may i know  why?

**Comment by ibrahimrehman1** [comment]
> In the class components earlier you wrote bind functions for state may i know why?

So that the this keyword points to the right context i.e. the instance of class. We have to do this otherwise, 'this' will be undefined. To avoid binding explicitly, we can use an **arrow function**.
